name: Build and Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check_commits.outputs.should_build }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for Feature Commits
        id: check_commits
        run: |
          HAS_FEATURE_COMMITS=false
          if git log --pretty=format:"%s" -n 1 | grep -E "^(feat:|add:|new:)"; then
            HAS_FEATURE_COMMITS=true
          fi
          echo "HAS_FEATURE_COMMITS=$HAS_FEATURE_COMMITS" >> $GITHUB_ENV
          echo "should_build=$HAS_FEATURE_COMMITS" >> $GITHUB_OUTPUT

  build_and_release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.outputs.should_build == 'true' || github.run_number == 1 || !contains(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Production
        run: npm run build:prod

      - name: Set Asset Path
        id: set_asset_path
        run: |
          echo "ASSET_PATH=build/reply-guy-prod.zip" >> $GITHUB_ENV

      - name: List Files
        run: ls -la

      - name: Extract Current Version
        id: extract_version
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Increment Version
        id: increment_version
        if: ${{ needs.build.outputs.should_build == 'true' }}
        run: |
          OLD_VERSION="${{ env.CURRENT_VERSION }}"
          IFS='.' read -r major minor patch <<< "$OLD_VERSION"
          NEW_PATCH=$((patch + 1))
          NEW_VERSION="$major.$minor.$NEW_PATCH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Set Default Version
        if: ${{ needs.build.outputs.should_build != 'true' }}
        run: |
          echo "NEW_VERSION=${{ env.CURRENT_VERSION }}" >> $GITHUB_ENV

      - name: Update package.json
        run: |
          jq --arg newVersion "${{ env.NEW_VERSION }}" '.version = $newVersion' package.json > package.json.tmp && mv package.json.tmp package.json

      - name: Commit and Tag
        if: ${{ needs.build.outputs.should_build == 'true' }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json
          git commit -m "chore: bump version to v${{ env.NEW_VERSION }}"
          git tag v${{ env.NEW_VERSION }}
          git push origin "v${{ env.NEW_VERSION }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: ${{ needs.build.outputs.should_build == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEW_VERSION }}
          release_name: Release v${{ env.NEW_VERSION }}
          draft: false
          prerelease: false
          body: |
            ## Installation Instructions

            To install the extension, follow these steps:

            1. Download the `reply-guy-v${{ env.NEW_VERSION }}-prod.zip` file from the release assets.
            2. Extract the zip file to a directory of your choice.
            3. Open your browser and go to the extensions page (chrome://extensions or edge://extensions).
            4. Enable 'Developer mode' at the top right corner.
            5. Click on 'Load unpacked' and select the extracted directory.

      - name: Upload Build to Release
        uses: actions/upload-release-asset@v1
        if: ${{ needs.build.outputs.should_build == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ASSET_PATH }}
          asset_name: reply-guy-v${{ env.NEW_VERSION }}-prod.zip
          asset_content_type: application/zip