name: Create Release

on:
  push:
    branches:
      - main
      - master
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Production
        run: npm run build:prod

      - name: Extract Version from Tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Generate Installation Instructions
        run: |
          echo "### Installation" > release_notes.txt
          echo "" >> release_notes.txt
          echo "1. Download the latest release (v$VERSION) from the [Releases](https://github.com/your-username/replyguy/releases) page." >> release_notes.txt
          echo "2. Unzip the downloaded file." >> release_notes.txt
          echo "3. Open your browser and navigate to `chrome://extensions/`." >> release_notes.txt
          echo "4. Enable 'Developer mode' using the toggle in the top right corner." >> release_notes.txt
          echo "5. Click on the 'Load unpacked' button and select the unzipped folder." >> release_notes.txt
          echo "" >> release_notes.txt
          echo "### Usage" >> release_notes.txt
          echo "" >> release_notes.txt
          echo "1. Navigate to Twitter/X." >> release_notes.txt
          echo "2. Look for the 🤖 button next to the reply button on any post." >> release_notes.txt
          echo "3. Click the button to generate and submit an AI-powered reply." >> release_notes.txt
          echo "4. The extension will automatically generate and post a contextually relevant reply." >> release_notes.txt

      - name: Upload Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/reply-guy-$VERSION-prod.zip
          asset_name: reply-guy-$VERSION-prod.zip
          asset_content_type: application/zip

      - name: Upload Installation Instructions to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release_notes-$VERSION.txt
          asset_name: release_notes-$VERSION.txt
          asset_content_type: text/plain
